// Popup anchor router. Firefox opens its panels with popup.openPopup(anchor, ...) where the anchor is
// a button in a toolbar that is no longer rendered: without help the application menu and extension
// popups do not open at all and permission doorhangers land at the window's top-left corner.
// One choke point per window: when the anchor has no box, hang the panel from Deer's own element,
// b.anchor('site') (the active pill) or b.anchor('menu') (the + circle), 8 px under the bar.
// Page <select> lists, autocomplete and context menus never come through here (they use
// openPopupAtScreen / openPopupAtScreenRect) and need nothing.
//
// Modules register their own anchors with b.setAnchor(kind, fn, { popups: ['some-panel-id'],
// position }): a popup whose id is listed is routed to that element (the downloads ring, an
// extension's button); the extensions and downloads authors do not edit this file.
//
// Recipe and limits: spikes/shell/RESULT.md section 5 and the verifier's corrections 3 and 11.
// Not covered: Firefox's own downloads panel (DownloadsButton.getAnchor() returns null, it never
// opens; Deer has its own). Popups anchored to another element inside #vitre-root (an extension
// button in the pill) keep the alignment their caller asked for.
// While a routed popup is open the bar is held on screen (auto-hide, full screen).
// In element full screen Deer's layer is not drawn: popups are left to Firefox then (a doorhanger
// opens at the window's top-left, as in stock) and re-anchored when full screen ends (browser.ts).
// Native popups are separate OS windows: they can be restyled, not made glass.
import type { Browser } from './browser';
import * as fx from './firefox';

const w = window as any;

/** What b.setAnchor registers. */
export interface AnchorRoute {
  element: () => Element | null;
  /** Popup ids routed to this anchor. */
  popups: string[];
  /** openPopup position, default 'bottomleft topleft'. */
  position?: string;
}

const DEFAULT_POSITION = 'bottomleft topleft';

/** Decide where a popup hangs. Returns null to leave Firefox's own anchor alone. */
function route(b: Browser, popup: any, anchor: any, hasCoords: boolean): { anchor: Element; position: string; x: number; y: number } | null {
  if (fx.inDOMFullscreen()) return null;
  const isElement = !!anchor && anchor.nodeType === 1;
  const id: string = popup.id || '';
  // A module asked for this popup by id.
  const own = b.anchorFor(id);
  if (own) {
    const to = b.anchor(own.kind);
    return { anchor: to, position: own.route.position ?? DEFAULT_POSITION, x: 0, y: 8 };
  }
  const doorhanger = id === fx.DOORHANGER_ID;
  // Firefox code that asked one of the hooks below for an anchor (PopupNotifications, page actions)
  // got the pill itself but passes its own alignment: realign those under the bar. Popups anchored
  // to anything else inside Deer's layer (an extension button in the pill, a module's own element)
  // are left alone.
  const ours = isElement && (anchor === b.anchor('site') || anchor === b.anchor('menu'));
  const hidden = isElement && !b.root.contains(anchor) && anchor.isConnected && anchor.getClientRects().length === 0;
  // Firefox code that looks for a visible anchor and finds none passes null (site information).
  const orphan = !anchor && !hasCoords && (doorhanger || popup.localName === 'panel');
  if (!ours && !hidden && !orphan) return null;
  const menu = id === 'appMenu-popup';
  const to = b.anchor(menu ? 'menu' : 'site');
  return { anchor: to, position: menu ? 'bottomright topright' : DEFAULT_POSITION, x: 0, y: 8 };
}

/**
 * DOMContentLoaded: wrap XULPopupElement.prototype.openPopup for this window.
 * Signature (dom/webidl/XULPopupElement.webidl): openPopup(anchor, options | position, x, y,
 * isContextMenu, attributesOverride, triggerEvent).
 */
export function installAnchors(b: Browser): void {
  const proto = w.XULPopupElement.prototype;
  if (proto.vitreRouted) return;
  const openPopup = proto.openPopup;
  proto.vitreRouted = true;
  proto.openPopup = function (this: any, anchor: any, options: any, x: any, y: any, isContextMenu: any, attributesOverride: any, triggerEvent: any) {
    let to = null;
    try {
      const o = options && typeof options === 'object' ? options : null;
      to = route(b, this, anchor, !!((o ? o.x : x) || (o ? o.y : y)));
    } catch (e) {
      console.error('Deer: popup routing failed', e);
    }
    if (!to) return openPopup.apply(this, arguments as any);
    // The popup hangs from the bar: keep the bar on screen (auto-hide, full screen) while it is open.
    try {
      const release = b.bar.hold('popup', true); // in place at once: the popup measures its anchor now
      const hidden = (e: Event): void => {
        if (e.target !== this) return; // a menu inside the panel closed
        this.removeEventListener('popuphidden', hidden);
        release();
      };
      this.addEventListener('popuphidden', hidden);
      // A popup that never opens (popupshowing cancelled) fires no popuphidden.
      window.setTimeout(() => {
        if (this.state === 'closed') release();
      }, 1000);
    } catch (e) {
      console.error('Deer: could not hold the bar for a popup', e);
    }
    const o = options && typeof options === 'object' ? options : { isContextMenu, attributesOverride, triggerEvent };
    return openPopup.call(this, to.anchor, {
      position: to.position,
      x: to.x,
      y: to.y,
      isContextMenu: !!o.isContextMenu,
      attributesOverride: !!o.attributesOverride,
      triggerEvent: o.triggerEvent || null,
    });
  };
}

/** Delayed startup: Firefox's lazy objects that ask for an anchor themselves. */
export function installAnchorsDelayed(b: Browser): void {
  const site = (): Element => b.anchor('site');
  try {
    // Permission doorhangers: the anchor Firefox asks for (an extension button in the pill, a
    // module's element) when it is visible inside Deer's layer, else the pill.
    fx.setDoorhangerAnchor((requested) => {
      try {
        if (requested && b.root.contains(requested) && (requested as HTMLElement).checkVisibility?.()) return requested;
      } catch {
        /* not an element */
      }
      return site();
    });
  } catch (e) {
    console.error('Deer: PopupNotifications anchor hook failed', e);
  }
  try {
    fx.setPageActionAnchor(site);
  } catch (e) {
    console.error('Deer: page action anchor hook failed', e);
  }
}
