// Build Vitre with esbuild.
//   node build.mjs              -> dist/
//   node build.mjs --out=dist-x -> another output folder (run it with: electron dist-x/main/main.js)
//   node build.mjs --watch
// Feature modules are discovered: any .ts file (or folder with index.ts) in
//   src/main/modules/        must export  register(ctx: MainContext)
//   src/renderer/modules/    must export  install(browser: Browser)
//   src/preload/page-modules/ runs for its side effects in every page
import * as esbuild from 'esbuild';
import { cpSync, existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join } from 'path';

const arg = (name) => process.argv.find((a) => a.startsWith(`--${name}=`))?.split('=')[1];
const out = arg('out') ?? 'dist';
const watch = process.argv.includes('--watch');

function discover(dir) {
  return readdirSync(dir)
    .filter((f) => !f.startsWith('_') && f !== 'index.ts')
    .filter((f) => (f.endsWith('.ts') && !f.endsWith('.d.ts')) || (statSync(join(dir, f)).isDirectory() && existsSync(join(dir, f, 'index.ts'))))
    .map((f) => f.replace(/\.ts$/, ''))
    .sort();
}

const mainMods = discover('src/main/modules');
writeFileSync('src/main/modules/_generated.ts', `// Generated by build.mjs. Do not edit.\n${mainMods.map((m, i) => `import * as m${i} from './${m}';`).join('\n')}\nexport const discovered = [${mainMods.map((m, i) => `{ name: '${m}', register: m${i}.register }`).join(', ')}];\n`);
const rendererMods = discover('src/renderer/modules');
writeFileSync('src/renderer/modules/_generated.ts', `// Generated by build.mjs. Do not edit.\n${rendererMods.map((m, i) => `import * as m${i} from './${m}';`).join('\n')}\nexport const discovered = [${rendererMods.map((m, i) => `{ name: '${m}', install: m${i}.install }`).join(', ')}];\n`);
const pageMods = discover('src/preload/page-modules');
writeFileSync('src/preload/page-modules/_generated.ts', `// Generated by build.mjs. Do not edit.\n${pageMods.map((m) => `import './${m}';`).join('\n')}\nexport {};\n`);

const common = { bundle: true, sourcemap: 'linked', logLevel: 'warning', target: 'es2022' };
const builds = [
  { ...common, entryPoints: ['src/main/main.ts'], outfile: `${out}/main/main.js`, platform: 'node', format: 'cjs', external: ['electron'] },
  { ...common, entryPoints: ['src/preload/chrome.ts'], outfile: `${out}/preload/chrome.js`, platform: 'node', format: 'cjs', external: ['electron'] },
  { ...common, entryPoints: ['src/preload/page.ts'], outfile: `${out}/preload/page.js`, platform: 'node', format: 'cjs', external: ['electron'] },
  { ...common, entryPoints: ['src/renderer/app.ts'], outfile: `${out}/renderer/app.js`, platform: 'browser', format: 'iife' },
];

mkdirSync(`${out}/renderer`, { recursive: true });
cpSync('src/renderer/index.html', `${out}/renderer/index.html`);
cpSync('src/renderer/styles.css', `${out}/renderer/styles.css`);
if (existsSync('src/renderer/assets')) cpSync('src/renderer/assets', `${out}/renderer/assets`, { recursive: true });

if (watch) {
  for (const b of builds) (await esbuild.context(b)).watch();
} else {
  await Promise.all(builds.map((b) => esbuild.build(b)));
  console.log(`built ${out}: main modules [${mainMods.join(', ')}], renderer modules [${rendererMods.join(', ')}], page modules [${pageMods.join(', ')}]`);
}
