// Build Vitre's chrome package with esbuild.
//
//   node tools/build.mjs                  -> build/            (runtime\vitre is a junction to it)
//   node tools/build.mjs --out=build-x    -> another output folder; run it with
//                                            python tools/run.py --app build-x ...
//   node tools/build.mjs --watch          rebuild on change (restart Vitre to load .sys.mjs / window.js)
//   node tools/build.mjs --modules=a,b    only bundle these discovered modules (plus the built-in
//                                         ones), e.g. while another author's module is half written
//   node tools/build.mjs --sourcemap      linked source maps next to each bundle
//
// What goes where (the package is flat; chrome://vitre/content/ maps to the output folder):
//   src/chrome.manifest                 -> chrome.manifest
//   src/modules/<Name>.sys.ts           -> modules/<Name>.sys.mjs   one ES module per top-level file,
//   src/actors/<Name>.sys.ts            -> actors/<Name>.sys.mjs    bundled with its relative imports;
//                                          chrome://, resource:// and moz-src:// imports stay as they are
//   src/window/main.ts                  -> window/window.js         one IIFE, loaded per browser window
//   src/pages/<name>/*.ts               -> pages/<name>/*.js        one IIFE per top-level .ts file
//   src/pages/<name>/<anything else>    -> pages/<name>/...         copied
//   src/skin/**, src/locales/**         -> skin/**, locales/**      copied
//
// __DEER_VERSION__ in any bundle is replaced by "version" in gecko/package.json (Settings › About
// shows it when no installed deer-version.json says otherwise; src/modules/VitreUpdater.sys.ts).
// __DEER_UPDATE_KEY__ is the release key's public half from gecko/update-key.txt (tools/release-key.mjs),
// or '' when there is none: with a key the updater accepts only releases whose SHA256SUMS.txt it signs.
//
// Auto-discovery (a file or a folder with index.ts; names starting with "_" and index.ts are skipped):
//   src/window/modules/<name>   must export  install(b: Browser)                -> window bundle
//   src/actors/page/<name>      may export   events, onEvent, onMessage         -> VitrePageChild.sys.mjs
// The index files are written as _generated.ts next to the modules (git-ignored, complete list, used by
// tsc); the bundles read the same index through a virtual module, so --modules never touches the file
// and parallel builds into different --out folders do not race.
import * as esbuild from 'esbuild';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, watch as fsWatch, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const arg = (name) => process.argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);
const flag = (name) => process.argv.includes(`--${name}`);

const outName = arg('out') ?? 'build';
if (!/^build(-[\w.-]+)?$/.test(outName)) {
  console.error(`--out must be "build" or "build-<name>" (got "${outName}")`);
  process.exit(2);
}
const OUT = join(ROOT, outName);
const watch = flag('watch');
const only = arg('modules')?.split(',').map((s) => s.trim()).filter(Boolean) ?? null;
/** Page modules that are part of the core and are never filtered out by --modules. */
const BUILTIN_PAGE_MODULES = ['core', 'inset', 'keys', 'pdf'];
const TARGET = 'firefox140';

const VERSION = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(VERSION ?? '')) {
  console.error(`package.json "version" must be X.Y.Z (got ${JSON.stringify(VERSION)})`);
  process.exit(2);
}
const UPDATE_KEY = existsSync(join(ROOT, 'update-key.txt')) ? readFileSync(join(ROOT, 'update-key.txt'), 'utf8').trim() : '';
if (UPDATE_KEY && !/^[A-Za-z0-9+/]{43}=$/.test(UPDATE_KEY)) {
  console.error('update-key.txt must hold the 32-byte Ed25519 public key in base64 (node tools/release-key.mjs new)');
  process.exit(2);
}

const WINDOW_MODULES = join(SRC, 'window', 'modules');
const PAGE_MODULES = join(SRC, 'actors', 'page');

function discover(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => !f.startsWith('_') && f !== 'index.ts')
    .filter((f) => (f.endsWith('.ts') && !f.endsWith('.d.ts')) || (statSync(join(dir, f)).isDirectory() && existsSync(join(dir, f, 'index.ts'))))
    .map((f) => f.replace(/\.ts$/, ''))
    .sort();
}

const header = '// Generated by tools/build.mjs. Do not edit.\n';
function windowIndex(names) {
  return (
    header +
    "import type { Browser } from '../browser';\n" +
    names.map((m, i) => `import * as m${i} from './${m}';`).join('\n') +
    `\nexport const discovered: { name: string; install: (b: Browser) => void }[] = [${names.map((m, i) => `{ name: '${m}', install: m${i}.install }`).join(', ')}];\n`
  );
}
function pageIndex(names) {
  return (
    header +
    "import type { PageModule } from '../page-api';\n" +
    names.map((m, i) => `import * as m${i} from './${m}';`).join('\n') +
    `\nexport const discovered: { name: string; module: PageModule }[] = [${names.map((m, i) => `{ name: '${m}', module: m${i} }`).join(', ')}];\n`
  );
}
function writeIfChanged(file, text) {
  if (existsSync(file) && readFileSync(file, 'utf8') === text) return;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
}

const picked = { window: [], page: [] };
/** Refresh the on-disk indexes (complete) and return the lists this build bundles (maybe filtered). */
function refreshIndexes() {
  const allWindow = discover(WINDOW_MODULES);
  const allPage = discover(PAGE_MODULES);
  writeIfChanged(join(WINDOW_MODULES, '_generated.ts'), windowIndex(allWindow));
  writeIfChanged(join(PAGE_MODULES, '_generated.ts'), pageIndex(allPage));
  picked.window = only ? allWindow.filter((m) => only.includes(m)) : allWindow;
  picked.page = only ? allPage.filter((m) => only.includes(m) || BUILTIN_PAGE_MODULES.includes(m)) : allPage;
}

/** Serve the two _generated.ts indexes from memory, so a filtered build needs no file of its own. */
const generatedIndex = {
  name: 'vitre-generated-index',
  setup(build) {
    build.onLoad({ filter: /[\\/]_generated\.ts$/ }, (args) => {
      refreshIndexes();
      const dir = dirname(args.path);
      if (dir === WINDOW_MODULES) return { contents: windowIndex(picked.window), loader: 'ts', resolveDir: dir, watchDirs: [dir] };
      if (dir === PAGE_MODULES) return { contents: pageIndex(picked.page), loader: 'ts', resolveDir: dir, watchDirs: [dir] };
      return undefined;
    });
  },
};

/**
 * The singleton rule, enforced: a .sys.ts file is bundled only as its own entry point. A relative
 * import of one from a window module, a page script or another singleton would give that bundle a
 * second copy of the singleton's state (listeners, `started` flags, pref observers). URL imports
 * (chrome://, resource://, moz-src://) stay external in the sys builds and are left to fail in the
 * others, as before.
 */
const singletonGuard = {
  name: 'vitre-singleton-guard',
  setup(build) {
    build.onResolve({ filter: /\.sys(\.ts|\.mjs)?$/ }, (args) => {
      if (args.kind === 'entry-point' || /^(chrome|resource|moz-src):/.test(args.path)) return undefined;
      return {
        errors: [
          {
            text: `"${args.path}" is a process singleton (.sys.ts). Import it by URL from another singleton (import { X } from 'chrome://vitre/content/modules/X.sys.mjs'), or use b.sys('X') with a type-only import (import type / typeof import) in window and page code.`,
          },
        ],
      };
    });
  },
};

const sysEntries = (dir) =>
  existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith('.sys.ts'))
        .sort()
        .map((f) => join(dir, f))
    : [];

const pageDirs = () =>
  existsSync(join(SRC, 'pages'))
    ? readdirSync(join(SRC, 'pages'))
        .filter((d) => statSync(join(SRC, 'pages', d)).isDirectory())
        .sort()
    : [];
const isScript = (f) => f.endsWith('.ts') && !f.endsWith('.d.ts');

function copyStatic() {
  mkdirSync(OUT, { recursive: true });
  cpSync(join(SRC, 'chrome.manifest'), join(OUT, 'chrome.manifest'));
  for (const dir of ['skin', 'locales']) {
    if (!existsSync(join(SRC, dir))) continue;
    rmSync(join(OUT, dir), { recursive: true, force: true });
    cpSync(join(SRC, dir), join(OUT, dir), { recursive: true });
  }
  for (const page of pageDirs()) {
    cpSync(join(SRC, 'pages', page), join(OUT, 'pages', page), {
      recursive: true,
      filter: (src) => !isScript(src),
    });
  }
}

function buildOptions() {
  const common = {
    bundle: true,
    target: TARGET,
    charset: 'utf8',
    legalComments: 'none',
    logLevel: 'warning',
    sourcemap: flag('sourcemap') ? 'linked' : false,
    absWorkingDir: ROOT,
    plugins: [generatedIndex, singletonGuard],
    define: { __DEER_VERSION__: JSON.stringify(VERSION), __DEER_UPDATE_KEY__: JSON.stringify(UPDATE_KEY) },
  };
  // System modules and actors: real ES modules. Other singletons are imported by URL and stay external
  // (a relative import of a stateful file from two entry points would give each its own copy).
  const sys = {
    ...common,
    format: 'esm',
    outExtension: { '.js': '.mjs' },
    external: ['chrome://*', 'resource://*', 'moz-src://*'],
  };
  const builds = [];
  const modules = sysEntries(join(SRC, 'modules'));
  const actors = sysEntries(join(SRC, 'actors'));
  if (modules.length) builds.push({ ...sys, entryPoints: modules, outdir: join(OUT, 'modules') });
  if (actors.length) builds.push({ ...sys, entryPoints: actors, outdir: join(OUT, 'actors') });
  // The per-window bundle is a classic script (loadSubScript): URL imports are not possible there, so
  // they are left unresolved on purpose and fail the build. Use b.sys('Name') and type-only imports.
  builds.push({ ...common, format: 'iife', entryPoints: [join(SRC, 'window', 'main.ts')], outfile: join(OUT, 'window', 'window.js') });
  for (const page of pageDirs()) {
    const scripts = readdirSync(join(SRC, 'pages', page)).filter((f) => isScript(f) && !f.startsWith('_'));
    if (scripts.length) {
      builds.push({ ...common, format: 'iife', entryPoints: scripts.map((f) => join(SRC, 'pages', page, f)), outdir: join(OUT, 'pages', page) });
    }
  }
  return { builds, names: { modules, actors } };
}

function clean() {
  if (!existsSync(OUT)) return;
  // Empty the folder but keep the folder itself: runtime\vitre and <profile>\chrome\vitre-app are
  // junctions pointing at it.
  for (const f of readdirSync(OUT)) rmSync(join(OUT, f), { recursive: true, force: true });
}

const base = (p) => p.split(sep).pop().replace(/\.sys\.ts$/, '');

async function buildOnce() {
  const started = Date.now();
  refreshIndexes();
  clean();
  copyStatic();
  const { builds, names } = buildOptions();
  await Promise.all(builds.map((b) => esbuild.build(b)));
  writeFileSync(
    join(OUT, 'build.json'),
    JSON.stringify({ built: new Date().toISOString(), windowModules: picked.window, pageModules: picked.page, pages: pageDirs() }, null, 1)
  );
  console.log(
    `built ${outName} in ${Date.now() - started} ms: sys [${names.modules.map(base).join(', ')}], actors [${names.actors.map(base).join(', ')}], ` +
      `window modules [${picked.window.join(', ')}], page modules [${picked.page.join(', ')}], pages [${pageDirs().join(', ')}]`
  );
}

async function buildWatch() {
  refreshIndexes();
  clean();
  copyStatic();
  const { builds } = buildOptions();
  for (const b of builds) await (await esbuild.context({ ...b, logLevel: 'info' })).watch();
  // Static files (css, html, manifest, locales) are not esbuild inputs: copy them again when they change.
  let timer = null;
  fsWatch(SRC, { recursive: true }, (_event, file) => {
    if (!file || /\.ts$/.test(file)) return;
    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        copyStatic();
        console.log(`copied static files (${relative(SRC, join(SRC, file))} changed)`);
      } catch (e) {
        console.error(String(e));
      }
    }, 80);
  });
  console.log(`watching src -> ${outName} (new sys modules, actors or pages need a restart of the watcher)`);
}

try {
  await (watch ? buildWatch() : buildOnce());
} catch (e) {
  // esbuild has already printed the errors.
  if (!e?.errors) console.error(e);
  process.exit(1);
}
